env:
    town: 'anytown_pd'
    state_vars:
        'day': 1
        'time': 0
        'tanks':
            - '41'
            - '42'
        'junctions':
            - '20'
    action_vars:
        - '78'
        - '79'
    # duration: 86400    # 1 day
    duration: 604800    # 1 week
    #duration: 6048    # for trials
    hyd_step: 600
    pattern_step: 300
    # pattern_file: null
    patterns:
        train: '../../demand_patterns/demand_patterns_train_low.csv'
        test: '../../demand_patterns/demand_patterns_test_low.csv'
    seed: null
    # update_every: 14400     # 4hours
    update_every: null
    bounds:
        day:
            min: 1
            max: 7
        time:
            min: 0
            max: 86400
        41_level:
            min: 3.048  #3.429 (5%)
            max: 10.668 #10,287 (95%)
        42_level:
            min: 3.048
            max: 10.668
        20_pressure:
            min: 10
            max: 100

agent:
    load: False
    load_as: 'saved_models/overflow.msh'
    batch_size: 64
    target_update_frequency: 10
    initial_replay_memory: 10
    max_replay_size: 10000

nn:
    hidden_size: 8

optimizer:
    lr: .00025

learning:
    epochs: 5
    train_episodes: 4
    train_frequency: 4
