env:
    town: 'ky3_pd'
    state_vars:
        'tanks':
            - 'T_1'
            - 'T_2'
            - 'T_3'
        'junctions':
            - 'I_Pump_1'
            - 'I_Pump_2'
            - 'I_Pump_3'
            - 'I_Pump_4'
            - 'I_Pump_5'
            - 'O_Pump_1'
            - 'O_Pump_2'
            - 'O_Pump_3'
            - 'O_Pump_4'
            - 'O_Pump_5'
    action_vars:
        - 'X_Pump_1'
        - 'X_Pump_2'
        - 'X_Pump_3'
        - 'X_Pump_4'
        - 'X_Pump_5'
    #duration: 86400    # 1 day
    duration: 604800    # 1 week
    hyd_step: 300
    pattern_step: 3600
    # pattern_file: null
    pattern_file: '../../demand_patterns/demands_anytown.csv'
    # update_every: 3600
    update_every: null
    bounds:
        time:
            min: 0
            max: 86400
        day:
            min: 1
            max: 7
        T_1_pressure:
            min: 0
            max: 100
        T_2_pressure:
            min: 0
            max: 100
        T_3_pressure:
            min: 10
            max: 100
        I_Pump_1:
            min: 10
            max: 100
        I_Pump_2:
            min: 10
            max: 100
        I_Pump_3:
            min: 10
            max: 100
        I_Pump_4:
            min: 10
            max: 100
        I_Pump_5:
            min: 10
            max: 100
        O_Pump_1:
            min: 10
            max: 100
        O_Pump_2:
            min: 10
            max: 100
        O_Pump_3:
            min: 10
            max: 100
        O_Pump_4:
            min: 10
            max: 100
        O_Pump_5:
            min: 10
            max: 100

agent:
    batch_size: 64
    target_update_frequency: 10
    initial_replay_memory: 1000
    max_replay_size: 10000
    fit_params:


nn:
    hidden_size: 8

optimizer:
    lr: .00025

learning:
    epochs: 10
    train_episodes: 1
    train_frequency: 4
